<?php
/**
 * Language file for messages du jour / MOTD (English)
 */

$lang['motd_title'] = 'Messages of the day';
$lang['motd_add'] = 'New message';
$lang['motd_edit'] = 'Edit message';
$lang['motd_view'] = 'View message';
$lang['motd_delete'] = 'Delete';

$lang['motd_field_title'] = 'Title';
$lang['motd_field_content'] = 'Content';
$lang['motd_field_level'] = 'Level';
$lang['motd_field_start_date'] = 'Start';
$lang['motd_field_end_date'] = 'End';
$lang['motd_field_target_type'] = 'Recipients';
$lang['motd_field_target_list_id'] = 'Mailing list';
$lang['motd_field_target_user_login'] = 'User';
$lang['motd_field_origin'] = 'Origin';

// field_long_name() looks these up (gvv_{table}_field_{field}) before
// falling back to the DB column COMMENT, which would otherwise leak our
// internal migration comments ("membres.mlogin", etc.) into form labels.
$lang['gvv_motd_messages_field_title'] = 'Title';
$lang['gvv_motd_messages_field_content'] = 'Content';
$lang['gvv_motd_messages_field_level'] = 'Level';
$lang['gvv_motd_messages_field_start_date'] = 'Start';
$lang['gvv_motd_messages_field_end_date'] = 'End';
$lang['gvv_motd_messages_field_target_type'] = 'Recipients';
$lang['gvv_motd_messages_field_target_list_id'] = 'Mailing list';
$lang['gvv_motd_messages_field_target_user_login'] = 'User';
$lang['gvv_motd_messages_field_origin'] = 'Origin';

$lang['motd_level_urgent'] = 'Urgent';
$lang['motd_level_important'] = 'Important';
$lang['motd_level_info'] = 'Info';
$lang['motd_level_alerte'] = 'Alert';

$lang['motd_target_all'] = 'All users';
$lang['motd_target_list'] = 'Mailing list';
$lang['motd_target_user'] = 'Single user';

$lang['motd_origin_admin'] = 'Administrator';
$lang['motd_origin_system'] = 'Generated by GVV';

$lang['motd_image_insert'] = 'Insert an image';
$lang['motd_image_upload_error'] = 'Failed to upload the image';

$lang['motd_error_invalid_target'] = 'The selected recipient is not valid (list or user not found).';
$lang['motd_error_dates_incoherent'] = 'The end date must be on or after the start date.';

$lang['motd_confirm_delete'] = 'Are you sure you want to delete this message?';
$lang['motd_no_messages'] = 'No message defined';

$lang['motd_no_title'] = '(no title)';
$lang['motd_sort_priority'] = 'Sort by priority';
$lang['motd_sort_date'] = 'Sort by date';
$lang['motd_replies_title'] = 'Replies';

$lang['motd_action_hide'] = 'Hide';
$lang['motd_action_hide_all'] = 'Hide all messages';
$lang['motd_action_acknowledge'] = 'I acknowledge this message';
$lang['motd_acknowledged_badge'] = 'Acknowledged';
$lang['motd_reply_placeholder'] = 'Your reply...';
$lang['motd_reply_submit'] = 'Reply';
$lang['motd_reply_to_reply'] = 'Reply';
$lang['motd_reply_cancel'] = 'Cancel';
$lang['motd_reply_replying_to'] = 'Replying to';
$lang['motd_confirm_hide_all'] = 'Hide all active messages?';
$lang['motd_error_reply_empty'] = 'The reply cannot be empty.';
$lang['motd_error_action_failed'] = 'An error occurred, please try again.';

$lang['motd_my_messages_title'] = 'All my messages';
$lang['motd_my_messages_link'] = 'All my messages';
$lang['motd_my_messages_empty'] = 'No message is currently addressed to you.';

/* End of file motd_lang.php */
/* Location: ./application/language/english/motd_lang.php */
