#!/bin/bash
# Manual smoke test for email list duplicate name validation
# This documents how to test the duplicate name validation feature

echo "=== Email List Duplicate Name Validation - Manual Test ==="
echo ""
echo "This test verifies that:"
echo "1. Creating a list with an existing name shows a specific error message"
echo "2. The page stays on the create form (no redirect)"
echo "3. The error message is clear and specific (not generic)"
echo ""
echo "PREREQUISITES:"
echo "- GVV application running (e.g., http://gvv.net or local dev server)"
echo "- User logged in with 'secretaire' or 'ca' role"
echo ""
echo "TEST STEPS:"
echo ""
echo "1. Navigate to: http://gvv.net/email_lists"
echo "   - You should see the list of existing email lists"
echo ""
echo "2. Note an existing list name (e.g., 'Test List')"
echo ""
echo "3. Click 'Nouvelle liste' button to create a new list"
echo "   - URL should be: http://gvv.net/email_lists/create"
echo ""
echo "4. Fill in the form with an EXISTING list name:"
echo "   - Nom: <existing-list-name>"
echo "   - Description: Test duplicate validation"
echo "   - Filtrer membres: Membres actifs seulement"
echo "   - Visible: checked"
echo ""
echo "5. Click 'Enregistrer' button"
echo ""
echo "EXPECTED RESULTS:"
echo "- Page stays on /email_lists/create (NOT redirected)"
echo "- Error message displayed at the top of the form:"
echo "  'Ce nom de liste existe déjà. Veuillez choisir un nom différent.'"
echo "  (French: This list name already exists. Please choose a different name.)"
echo "- Form fields retain their values (description, filters, etc.)"
echo "- Name field is highlighted with red border (Bootstrap is-invalid class)"
echo ""
echo "BEFORE THE FIX:"
echo "- Generic error: 'Erreur lors de la création de la liste'"
echo "- Page might not reload immediately"
echo "- No clear indication that the name is duplicate"
echo ""
echo "AFTER THE FIX:"
echo "- Specific error: 'Ce nom de liste existe déjà. Veuillez choisir un nom différent.'"
echo "- Validation happens BEFORE database insert attempt"
echo "- Form re-displays immediately with clear error message"
echo ""
echo "ADDITIONAL TESTS:"
echo ""
echo "6. Test with a UNIQUE name:"
echo "   - Change name to something unique (e.g., 'Test List 2024-XX-XX')"
echo "   - Click 'Enregistrer'"
echo "   - Should succeed and redirect to edit page"
echo ""
echo "7. Test UPDATE with same name (should work):"
echo "   - Edit an existing list"
echo "   - Keep the same name, change description"
echo "   - Click 'Enregistrer'"
echo "   - Should succeed (can keep same name during update)"
echo ""
echo "8. Test UPDATE with duplicate name (should fail):"
echo "   - Edit list 'A'"
echo "   - Change name to existing list 'B'"
echo "   - Click 'Enregistrer'"
echo "   - Should show duplicate error"
echo ""
echo "FILES MODIFIED:"
echo "- application/controllers/email_lists.php"
echo "  - Added validation callback check_name_unique()"
echo "  - Added callback to form_validation rules in store() and update()"
echo ""
echo "- application/models/email_lists_model.php"
echo "  - Added name_exists() method to check for duplicates"
echo ""
echo "- application/language/french/email_lists_lang.php"
echo "- application/language/english/email_lists_lang.php"
echo "- application/language/dutch/email_lists_lang.php"
echo "  - Added 'email_lists_name_duplicate' translation"
echo ""
