<?php
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

/**
 * Migration 143: Create Messages du jour (MOTD) tables
 *
 * Creates tables for the MOTD module:
 * - motd_messages: messages created by admins or generated by GVV (alarms)
 * - motd_media: images uploaded and referenced from message content
 * - motd_replies: replies to a message, visible to its recipients and author
 * - motd_user_message_state: per user/message hidden + acknowledged state
 * - motd_user_prefs: per user persistent display preferences
 *
 * "Acting user" columns (created_by/updated_by on every table,
 * motd_replies.author_login, motd_user_message_state.user_login,
 * motd_user_prefs.user_login) have no FK to `membres`: they identify
 * whoever is logged in and acting (creating/editing a message, replying,
 * hiding, acknowledging, setting a preference), which is not necessarily a
 * club member - legacy DX_Auth admin accounts (e.g. `testadmin`) have no
 * matching `membres` row. They remain plain audit-trail VARCHAR values, like
 * `reservation_reminder_log.created_by`/`updated_by`. `target_user_login` on
 * `motd_messages` (an actual message recipient, not an actor) keeps its FK
 * to `membres` and is validated by `Motd_model::is_target_valid()`.
 *
 * @see doc/prds/messages_du_jour_prd.md
 * @see doc/design_notes/messages_du_jour_design.md
 */
class Migration_Create_motd_tables extends CI_Migration {

    protected $migration_number;

    function __construct() {
        parent::__construct();
        $this->migration_number = 143;
    }

    private function run_queries($sqls = array()) {
        $errors = 0;
        foreach ($sqls as $sql) {
            gvv_info("Migration sql: " . $sql);
            if (!$this->db->query($sql)) {
                $mysql_msg = $this->db->_error_message();
                $mysql_error = $this->db->_error_number();
                gvv_error("Migration error: code=$mysql_error, msg=$mysql_msg");
                $errors += 1;
            }
        }
        return $errors;
    }

    public function up() {
        $errors = 0;

        $sqls = array(
            // Table: motd_messages - messages du jour (admin ou generes par GVV)
            "CREATE TABLE IF NOT EXISTS `motd_messages` (
                `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
                `title` VARCHAR(255) NULL COMMENT 'Titre optionnel',
                `content` TEXT NOT NULL COMMENT 'Contenu Markdown',
                `level` ENUM('urgent', 'important', 'info', 'alerte') NULL COMMENT 'Niveau optionnel',
                `start_date` DATETIME NOT NULL COMMENT 'Debut de periode d affichage',
                `end_date` DATETIME NOT NULL COMMENT 'Fin de periode d affichage',
                `target_type` ENUM('all', 'list', 'user') NOT NULL DEFAULT 'all' COMMENT 'Type de cible',
                `target_list_id` INT(11) NULL COMMENT 'Liste de diffusion ciblee (email_lists.id)',
                `target_user_login` VARCHAR(25) NULL COMMENT 'Utilisateur unique cible (membres.mlogin)',
                `origin` ENUM('admin', 'system') NOT NULL DEFAULT 'admin' COMMENT 'Origine du message',
                `source_type` VARCHAR(50) NULL COMMENT 'Tag libre pour messages generes (ex: alarm_medical)',
                `source_ref` VARCHAR(100) NULL COMMENT 'Reference libre vers l entite source',
                `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                `created_by` VARCHAR(25) NULL COMMENT 'Acteur (pas de FK, cf. commentaire de migration)',
                `updated_by` VARCHAR(25) NULL COMMENT 'Acteur (pas de FK, cf. commentaire de migration)',
                PRIMARY KEY (`id`),
                KEY `idx_motd_messages_period` (`start_date`, `end_date`),
                KEY `idx_motd_messages_target_type` (`target_type`),
                KEY `idx_motd_messages_target_list` (`target_list_id`),
                KEY `idx_motd_messages_target_user` (`target_user_login`),
                CONSTRAINT `fk_motd_messages_target_list` FOREIGN KEY (`target_list_id`)
                    REFERENCES `email_lists` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
                CONSTRAINT `fk_motd_messages_target_user` FOREIGN KEY (`target_user_login`)
                    REFERENCES `membres` (`mlogin`) ON DELETE CASCADE ON UPDATE CASCADE
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci
            COMMENT='Messages du jour'",

            // Table: motd_media - images televersees referencees dans le contenu
            "CREATE TABLE IF NOT EXISTS `motd_media` (
                `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
                `message_id` INT(11) UNSIGNED NULL COMMENT 'Message associe (motd_messages.id)',
                `filename` VARCHAR(255) NOT NULL COMMENT 'Nom de stockage non predictible',
                `original_filename` VARCHAR(255) NOT NULL COMMENT 'Nom de fichier d origine',
                `mime_type` VARCHAR(100) NOT NULL COMMENT 'Type MIME reel detecte',
                `size_bytes` INT(11) UNSIGNED NOT NULL COMMENT 'Taille en octets',
                `sha256` CHAR(64) NOT NULL COMMENT 'Empreinte SHA-256 du fichier',
                `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                `created_by` VARCHAR(25) NULL COMMENT 'Acteur (pas de FK, cf. commentaire de migration)',
                `updated_by` VARCHAR(25) NULL COMMENT 'Acteur (pas de FK, cf. commentaire de migration)',
                PRIMARY KEY (`id`),
                KEY `idx_motd_media_message` (`message_id`),
                CONSTRAINT `fk_motd_media_message` FOREIGN KEY (`message_id`)
                    REFERENCES `motd_messages` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci
            COMMENT='Images televersees pour les messages du jour'",

            // Table: motd_replies - reponses a un message
            "CREATE TABLE IF NOT EXISTS `motd_replies` (
                `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
                `message_id` INT(11) UNSIGNED NOT NULL COMMENT 'Message associe (motd_messages.id)',
                `parent_reply_id` INT(11) UNSIGNED NULL COMMENT 'Reponse parente (reponse d un admin a une reponse)',
                `author_login` VARCHAR(25) NOT NULL COMMENT 'Acteur (pas de FK, cf. commentaire de migration)',
                `content` TEXT NOT NULL COMMENT 'Contenu Markdown',
                `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                `created_by` VARCHAR(25) NULL COMMENT 'Acteur (pas de FK, cf. commentaire de migration)',
                `updated_by` VARCHAR(25) NULL COMMENT 'Acteur (pas de FK, cf. commentaire de migration)',
                PRIMARY KEY (`id`),
                KEY `idx_motd_replies_message` (`message_id`),
                KEY `idx_motd_replies_parent` (`parent_reply_id`),
                CONSTRAINT `fk_motd_replies_message` FOREIGN KEY (`message_id`)
                    REFERENCES `motd_messages` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
                CONSTRAINT `fk_motd_replies_parent` FOREIGN KEY (`parent_reply_id`)
                    REFERENCES `motd_replies` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci
            COMMENT='Reponses aux messages du jour'",

            // Table: motd_user_message_state - etat individuel (masque, pris connaissance)
            "CREATE TABLE IF NOT EXISTS `motd_user_message_state` (
                `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
                `message_id` INT(11) UNSIGNED NOT NULL COMMENT 'Message associe (motd_messages.id)',
                `user_login` VARCHAR(25) NOT NULL COMMENT 'Acteur (pas de FK, cf. commentaire de migration)',
                `hidden` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Message masque par l utilisateur',
                `acknowledged` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Pris connaissance',
                `acknowledged_at` DATETIME NULL COMMENT 'Date de prise de connaissance',
                `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                `created_by` VARCHAR(25) NULL COMMENT 'Acteur (pas de FK, cf. commentaire de migration)',
                `updated_by` VARCHAR(25) NULL COMMENT 'Acteur (pas de FK, cf. commentaire de migration)',
                PRIMARY KEY (`id`),
                UNIQUE KEY `uk_motd_user_message_state` (`message_id`, `user_login`),
                KEY `idx_motd_user_message_state_user` (`user_login`),
                CONSTRAINT `fk_motd_ums_message` FOREIGN KEY (`message_id`)
                    REFERENCES `motd_messages` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci
            COMMENT='Etat utilisateur par message (masque, pris connaissance)'",

            // Table: motd_user_prefs - preferences d affichage persistantes
            "CREATE TABLE IF NOT EXISTS `motd_user_prefs` (
                `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
                `user_login` VARCHAR(25) NOT NULL COMMENT 'Acteur (pas de FK, cf. commentaire de migration)',
                `section_collapsed` TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Section repliee par defaut',
                `sort_by` ENUM('priority', 'date') NOT NULL DEFAULT 'priority' COMMENT 'Critere de tri',
                `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                `created_by` VARCHAR(25) NULL COMMENT 'Acteur (pas de FK, cf. commentaire de migration)',
                `updated_by` VARCHAR(25) NULL COMMENT 'Acteur (pas de FK, cf. commentaire de migration)',
                PRIMARY KEY (`id`),
                UNIQUE KEY `uk_motd_user_prefs_user` (`user_login`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci
            COMMENT='Preferences d affichage des messages du jour par utilisateur'",
        );

        $errors += $this->run_queries($sqls);

        if ($errors > 0) {
            gvv_error("Migration 143: $errors error(s) while creating MOTD tables");
        }
    }

    public function down() {
        $sqls = array(
            "DROP TABLE IF EXISTS `motd_user_prefs`",
            "DROP TABLE IF EXISTS `motd_user_message_state`",
            "DROP TABLE IF EXISTS `motd_replies`",
            "DROP TABLE IF EXISTS `motd_media`",
            "DROP TABLE IF EXISTS `motd_messages`",
        );

        $this->run_queries($sqls);
    }
}
