<?php
require_once 'PhpunitGVVSelenium.php';

class PhpunitPlaneurs extends PhpunitGVVSelenium {

    public function testComptesCreate() {
        $this->login();    
                
        $this->click("link=Machines");
        $this->waitForPageToLoad("30000");
        $this->click("css=img.icon");
        $this->waitForPageToLoad("30000");
        $this->type("name=mpconstruc", "Alexander Schleicher");
        $this->type("name=mpmodele", "Asw20");
        $this->type("name=mpimmat", "F-CERP");
        $this->type("name=mpnumc", "UP");
        $this->click("name=mptreuil");
        $this->click("id=Privé");
        $this->select("name=mprix", "label=Heure non facturée : 0.00");
        $this->select("name=mprix_forfait", "label=Heure non facturée : 0.00");
        $this->click("name=button");
        $this->waitForPageToLoad("30000");
        $this->click("css=img.icon");
        $this->waitForPageToLoad("30000");
        $this->type("name=mpconstruc", "Grob");
        $this->type("name=mpmodele", "G103");
        $this->type("name=mpimmat", "F-CFYD");
        $this->type("name=mpnumc", "T83");
        $this->type("name=mpbiplace", "2");
        $this->click("name=mptreuil");
        $this->select("name=mprix", "label=Heure de vol biplace : 27.00");
        $this->select("name=mprix_forfait", "label=Heure de vol au forfait : 10.00");
        $this->click("name=button");
        $this->waitForPageToLoad("30000");
        $this->click("css=img.icon");
        $this->waitForPageToLoad("30000");
        $this->type("name=mpmodele", "Pégase");
        $this->type("name=mpconstruc", "Centrair");
        $this->type("name=mpimmat", "F-CGFN");
        $this->type("name=mpnumc", "3S");
        $this->click("name=mptreuil");
        $this->click("id=Privé");
        $this->select("name=mprix", "label=Heure non facturée : 0.00");
        $this->select("name=mprix_forfait", "label=Heure non facturée : 0.00");
        $this->click("name=button");
        $this->waitForPageToLoad("30000");
        $this->click("css=img.icon");
        $this->waitForPageToLoad("30000");
        $this->type("name=mpconstruc", "Centrair");
        $this->type("name=mpmodele", "Asw20");
        $this->type("name=mpimmat", "F-CGKS");
        $this->type("name=mpnumc", "WE");
        $this->select("name=mprix", "label=Heure non facturée : 0.00");
        $this->select("name=mprix_forfait", "label=Heure non facturée : 0.00");
        $this->click("id=Privé");
        $this->click("name=button");
        $this->waitForPageToLoad("30000");
        $this->click("css=img.icon");
        $this->waitForPageToLoad("30000");
        $this->type("name=mpconstruc", "Centrair");
        $this->type("name=mpmodele", "Pégase");
        $this->type("name=mpimmat", "F-CGNP");
        $this->type("name=mpnumc", "Y31");
        $this->click("name=mptreuil");
        $this->select("name=mprix", "label=Heure de vol monoplace : 10.00");
        $this->select("name=mprix_forfait", "label=Heure de vol au forfait : 10.00");
        $this->click("name=button");
        $this->waitForPageToLoad("30000");
        $this->click("css=img.icon");
        $this->waitForPageToLoad("30000");
        $this->type("name=mpmodele", "DG400");
        $this->type("name=mpconstruc", "Glaser-Dirks");
        $this->type("name=mpimmat", "F-CGRD");
        $this->type("name=mpnumc", "RD");
        $this->click("name=mpautonome");
        $this->click("name=mptreuil");
        $this->click("id=Privé");
        $this->select("name=mprix", "label=Heure non facturée : 0.00");
        $this->select("name=mprix_forfait", "label=Heure non facturée : 0.00");
        $this->click("name=button");
        $this->waitForPageToLoad("30000");
        $this->click("css=img.icon");
        $this->waitForPageToLoad("30000");
        $this->type("name=mpmodele", "PW-5");
        $this->type("name=mpconstruc", "Politechnika Warszawska");
        $this->type("name=mpimmat", "F-CICA");
        $this->type("name=mpnumc", "CA");
        $this->click("name=mptreuil");
        $this->select("name=mprix", "label=Heure de vol monoplace : 10.00");
        $this->select("name=mprix_forfait", "label=Heure de vol au forfait : 10.00");
        $this->click("name=button");
        $this->waitForPageToLoad("30000");
        $this->click("css=img.icon");
        $this->waitForPageToLoad("30000");
        $this->type("name=mpconstruc", "Alexander Schleicher");
        $this->type("name=mpmodele", "Ask21");
        $this->type("name=mpimmat", "F-CJRG");
        $this->type("name=mpnumc", "RG");
        $this->type("name=mpbiplace", "2");
        $this->click("name=mptreuil");
        $this->select("name=mprix", "label=Heure de vol biplace : 27.00");
        $this->select("name=mprix_forfait", "label=Heure de vol au forfait : 10.00");
        $this->click("name=button");
        $this->waitForPageToLoad("30000");
        $this->assertTrue($this->isTextPresent("Asw20"));
        $this->assertTrue($this->isTextPresent("Alexander Schleicher"));
        $this->assertTrue($this->isTextPresent("F-CERP"));
        $this->assertTrue($this->isTextPresent("UP"));
        $this->assertTrue($this->isTextPresent("Privé"));
        $this->assertTrue($this->isTextPresent("PW-5"));
        $this->assertTrue($this->isTextPresent("Politechnika Warszawska"));
        $this->click("xpath=(//img[@title='Changer'])[5]");
        $this->waitForPageToLoad("30000");
        $this->click("css=input[type=\"submit\"]");
        $this->waitForPageToLoad("30000");
    }
}
?>